logging:
  level:
    root: DEBUG
    com.marketmate: DEBUG
    org.springframework: INFO
    # 調査時のみ有効に（コミットしない）
    # org.springframework.security: DEBUG
    # Hibernate 6 のバインド値まで
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

app:
  cors:
    allowed-origins: "http://localhost:3000"
  cookie:
    secure: false