name: Docker Publish (Web/API → GHCR)

on:
  workflow_dispatch:
    inputs:
      target:
        description: "web / api / both"
        required: true
        default: "both"
        type: choice
        options: [web, api, both]
      version:
        description: "tag (e.g. v1.0.0). empty = short SHA"
        required: false
        type: string
  push:
    tags:
      - "v*"

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  OWNER: ${{ github.repository_owner }}
  REPO: ${{ github.event.repository.name }}

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [web, api]

    steps:
      - uses: actions/checkout@v4

      - id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.OWNER }}/${{ env.REPO }}-${{ matrix.service }}
          tags: |
            type=raw,value=${{ github.event_name == 'workflow_dispatch' && inputs.version != '' && inputs.version || '' }}
            type=raw,value=latest,enable=${{ github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && inputs.version != '') }}
            type=sha,format=short,enable=${{ github.event_name == 'workflow_dispatch' && (inputs.version == '' || inputs.version == null) }}
            type=ref,event=tag,enable=${{ github.event_name == 'push' }}

      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/setup-buildx-action@v3

      - name: Build & Push ${{ matrix.service }}
        uses: docker/build-push-action@v5
        if: |
          github.event_name == 'push' ||
          inputs.target == 'both' ||
          (inputs.target == 'web' && matrix.service == 'web') ||
          (inputs.target == 'api' && matrix.service == 'api')
        with:
          context: ${{ matrix.service == 'web' && 'marketmate' || 'marketmate-server' }}
          file: ${{ matrix.service == 'web' && 'marketmate/Dockerfile' || 'marketmate-server/Dockerfile' }}
          platforms: linux/amd64
          push: true
          provenance: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
